# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "Kwartoverbier"
site_name: "Kwartoverbier.nl"
subtitle: 16.15u is tijd voor bier
email: hallo@kwartoverbier.nl
author: Ruben Janssen
author_email: hallo@rubenjanssen.nl
description: "Is het al kwartoverbier?"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://kwartoverbier.nl" # the base hostname & protocol for your site
permalink: "https://kwartoverbier.nl" # the base hostname & protocol for your site
include: [static,".htaccess"]
exclude: ["*.xml","*.log","Gemfile", "*.json", "images", "deploy" ,"node_modules", "gulpfile.js", "autoprefixer.yml", "r.js", "amd-optimize-config.json", "README.MD"]
version: 2.0

sass:
  style: compressed
autowrite: true
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: [local]


#gems: [jekyll-assets, autoprefixer-rails]


assets:
  compress:
    css: true
    js: true
  cache: false
  digest: true
  sources:
    - scss
    - static/css
    - static/fonts
    - static/js

#features:
#  liquid: true

# Where things are
source: .
destination: ./www


# Defaults
#defaults:
#  - scope:
#      path: ""
#      type: "products"
#    values:
#      layout: product

# Collections
collections:
  pages:
    output: true
    permalink: /:title
  evenementen:
    output: false
  onzeleden:
    output: false


# Build settings
markdown: kramdown
